### ISSUE TITLE
Question: Is it possible to search through API using a phrase?

### ISSUE THREAD

**Issue by mbojan** [CeON/saos#448]
How to look up judgements with specific judges? When searching for a specific judge with, say

https://saos-test.icm.edu.pl/api/search/judgments?judgeName=%22aleksandra%20%C5%BCurawska%22

we are getting all judgements with judges whose name is `Aleksandra` (not necesarily `Żurawska`) and judges whose family name is `Żurawska` (not necesarily `Aleksandra`) etc.

Is it possible to search using exact phrase?

PS. Of interest also to @bartekch

**Comment by lukdumi** [comment]
I guess it's a kind of mistake. In my view searching by a judge name should take into accout the whole phrase. So, for example searching by "Jan Nowak" should give all the judgments with the judge name equal to "Jan Nowak" (or "Nowak Jan"). Judge names like 'Jan Kowalski', 'Adam Nowak' or even "Jan Nowakowski" shouldn't be included in the search result.

**Comment by lukdumi** [comment]
It'll be corrected by #451

**Comment by lukdumi** [comment]
See also: #452 and #453

**Comment by mbojan** [comment]
Thanks, we're looking forward have these resolved.

So the goal is to have `or` and `and` as special keywords in the search query? We have also tried `"'Aleksandra Żurawska'"` too (two pairs of quotes to mark the phrase), but the result was the same.

**Comment by lukdumi** [comment]
Yes, you're right. By default the effect will be as I wrote before but it'll be possible to use some special control phrases to change the search action.
