### ISSUE TITLE
Searching by judgmentTypes doesn't work

### ISSUE THREAD

**Issue by bartekch** [CeON/saos#504]
According to documentation as well as queryTemplate the following query should work
https://saos-test.icm.edu.pl/api/search/judgments?judgmentTypes=SENTENCE
But it doesn't, with error
{"error":{"httpStatus":"500","name":"INTERNAL ERROR","propertyName":null,"message":"java.lang.String cannot be cast to java.lang.Enum","moreInfo":"${restful.api.error.documentation.site}GENERAL_INTERNAL_ERROR"}}

Unfortunately I have no idea what this error means.

The same query works ok in GUI.
https://saos-test.icm.edu.pl/search?judgmentTypes=SENTENCE

**Comment by lukdumi** [comment]
OK, we'll check & correct it next week.
