### ISSUE TITLE
How exactly does OR operator work?

### ISSUE THREAD

**Issue by bartekch** [CeON/saos#518]
I am confused about how "OR" works in searching.
Consider I want to search for judgments that contain word "kara" OR words "dobra" and "osobiste" (but not treat "dobra osobiste" as a single phrase, so without quation marks). So I use `all=kara OR dobra osobiste` and it seems to work as wished. But if we write it in reverse order, `dobra osobiste OR kara` it gives different results, rather like we were looking for something like `all=dobra (osobiste OR kara)`. 
So it looks like "OR" has precedence in second case but not in the first one. Correct me if I am wrong.

It's totally counterituitive for me, there should be some clear rules of precedence, or, ideally, possibility to use parentheses to force correct execution order (in my example `(dobra osobiste) OR kara` or `kara OR (dobra osobiste)`.

**Comment by madryk** [comment]
Operator OR have precedence in both of your examples
Let's look at query `all=kara OR dobra osobiste`
If it would be searched like `kara OR (dobra osobiste)` then search results would contain for example judgment I ACa 756/12 with id: 34 (it has term `kara` but not `dobra

**Comment by madryk** [comment]
In general when implementing search we tried to mimic behaviour of google search. In cases like this (mixing OR with default 'and' operator) it seems that they also give operator OR higher priority.

**Comment by bartekch** [comment]
Right, I haven't looked carefully enough. 
Anyway, do you plan to develop search engine so it will be possible to ask queries like my example (`all=kara OR (dobra osobiste)`)? As far as I know google search doesn't respect parentheses.

**Comment by madryk** [comment]
We don't have in plans to include support for parentheses.

**Comment by bartekch** [comment]
OK. One more question - what about mixing OR and "-" operators together? I've discovered that searching for `all = rozwód OR -alimenty` gives identical results as `all = rozwód -alimenty` (and vice versa, search results for `all=-rozwód OR alimenty` and `all=-rozwód alimenty` are identical). So it looks like OR has no effect here. But `-rozwód OR -alimenty` gives no results. Could you explain this?

**Comment by madryk** [comment]
It is clearly a bug. I moved it to #564
