### ISSUE TITLE
"Gateway Timeout" while search includes some specific judgments

### ISSUE THREAD

**Issue by bartekch** [CeON/saos#573]
Whean search result includes judgments with id 31382 or 52387 we get an error "504 Gateway Time-out" (both GUI and API).
Here links to search result where judgment 31382 should be

https://saos-test.icm.edu.pl/api/search/judgments?pageSize=1&pageNumber=201&ccCourtId=75&judgmentDateTo=2015-02-23&sortingField=JUDGMENT_DATE&sortingDirection=ASC

in GUI
https://saos-test.icm.edu.pl/search?dateFrom=11-04-2013&dateTo=11-04-2013&courtType=COMMON&commonCourtId=75&size=20&sort=JUDGMENT_DATE%2Cdesc

and judgment 52387
https://saos-test.icm.edu.pl/api/search/judgments?pageSize=1&pageNumber=1071&ccCourtId=35&judgmentDateTo=2015-02-23&sortingField=JUDGMENT_DATE&sortingDirection=ASC

However in dump both judgments are returned correctly
https://saos-test.icm.edu.pl/api/judgments/31382
https://saos-test.icm.edu.pl/api/judgments/52387

These are only cases that I've found, maybe there are more.

**Comment by madryk** [comment]
Hey!
Thanks for noticing this problem.
It was caused by insufficient amount of memory allocated for solr.

**Comment by bartekch** [comment]
It looks OK now, have you changed anything?

**Comment by madryk** [comment]
I've raised memory limit for solr
