### ISSUE TITLE
Dump api - pageSize description is wrong + allow bigger size

### ISSUE THREAD

**Issue by lukdumi** [CeON/saos#711]
"pageSize": {"value": 100,
"description": "Represents maximum number of items on the page",
"allowedValues": "Any positive integer"

but if pageSize>100 then error.

To do:
- the parameter description should show the maximum allowed value,
- max value should be 500

**Comment by madryk** [comment]
Due to long processing when page size is big, I've decided to leave max allowed page size (100).

**Comment by madryk** [comment]
Lower limit for pageSize was also added and set to 10
