### ISSUE TITLE
Sorting judges in JudgmetDetailsControllers - improve the solution

### ISSUE THREAD

**Issue by lukdumi** [CeON/saos#713]
Judgment judgment = judgmentDetailsSortService.sortJudges(judgmentEnrichmentService.findOneAndEnrich(judgmentId)

It's a bad idea to change the read object. You could do the sorting in a nicer way on jsp.

**Comment by pawelczak** [comment]
JudgeSortService

public void sort(List<Judge> judges) {
    judges.sort(Comparator)
}
